### ISSUE TITLE
Add Borg

### ISSUE THREAD

**Issue by vibl** [gilbertchen/benchmarking#1]
I'm sure it's already on your todo list, but I'd just like to point out that most Attic users seem to have switched to Borg, which is an actively maintained fork, and one of the most recommended backup solutions in HN, Reddit and blogs.

**Comment by gilbertchen** [comment]
I like to call it Attic, out of the respect to the original author, but it was actually BorgBackup version 1.1.0b6, as you can see from the Setup section.

**Comment by vibl** [comment]
Oh, ok...
